### ISSUE TITLE
Unable to run "docker-compose up" , "angularjs" and "worker" services are failing.

### ISSUE THREAD

**Issue by diningPhilosopher64** [Cloud-CV/EvalAI-ngx#249]
## I'm submitting a

(Check one with "x" from given options)
- [x] Bug report
- [ ] Feature request

## Current behavior

(Check screenshot for better understanding)
The "worker" service fails with the following output (exits with status code 1) :
`
worker_1     | TypeError: eval() arg 1 must be a string, bytes or code object
worker_1     | [2019-12-26 13:31:40] INFO Using /tmp/tmph_lyqpk3 as temp directory to store data
worker_1     | Traceback (most recent call last):
worker_1     |   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
worker_1     |     "__main__", mod_spec)
worker_1     |   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
worker_1     |     exec(code, run_globals)
worker_1     |   File "/code/scripts/workers/submission_worker.py", line 751, in <module>
worker_1     |     main()
worker_1     |   File "/code/scripts/workers/submission_worker.py", line 680, in main
worker_1     |     if eval(LIMIT_CONCURRENT_SUBMISSION_PROCESSING):
worker_1     | TypeError: eval() arg 1 must be a string, bytes or code object
`

The "angularjs" service fails with the following output(exits with status code 1)"
`
evalai_ngx   | Schema validation failed with the following errors:                                                                          
evalai_ngx   |   Data path ".builders['app-shell']" should have required property 'class'.                                                        
evalai_ngx   | Error: Schema validation failed with the following errors:                                                                     
evalai_ngx   |   Data path ".builders['app-shell']" should have required property 'class'.                                                        
evalai_ngx   |     at MergeMapSubscriber.project (/code/node_modules/@angular-devkit/core/src/workspace/workspace.js:215:42)                      
evalai_ngx   |     at MergeMapSubscriber._tryNext (/code/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/mergeMap.js:69:27$
evalai_ngx   |     at MergeMapSubscriber._next (/code/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/mergeMap.js:59:18)   
evalai_ngx   |     at MergeMapSubscriber.Subscriber.next (/code/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
evalai_ngx   |     at MergeMapSubscriber.notifyNext (/code/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/mergeMap.js:92:$
6)                                                                                                                                            
evalai_ngx   |     at InnerSubscriber._next (/code/node_modules/@angular-devkit/core/node_modules/rxjs/internal/InnerSubscriber.js:28:21)        
evalai_ngx   |     at InnerSubscriber.Subscriber.next (/code/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
evalai_ngx   |     at MapSubscriber._next (/code/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/map.js:55:26)
evalai_ngx   |     at MapSubscriber.Subscriber.next (/code/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
evalai_ngx   |     at SwitchMapSubscriber.notifyNext (/code/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:86
:26)
evalai_ngx   |     at InnerSubscriber._next (/code/node_modules/@angular-devkit/core/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
evalai_ngx   |     at InnerSubscriber.Subscriber.next (/code/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
evalai_ngx   |     at /code/node_modules/@angular-devkit/core/node_modules/rxjs/internal/util/subscribeTo.js:17:28
evalai_ngx   |     at Object.subscribeToResult (/code/node_modules/@angular-devkit/core/node_modules/rxjs/internal/util/subscribeToResult.js:10:45
)
evalai_ngx   |     at SwitchMapSubscriber._innerSub (/code/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:65:
54)
evalai_ngx   |     at SwitchMapSubscriber._next (/code/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:55:14)
`

## Expected behavior

Should be able to start all containers without any issues.

## Steps to reproduce

Clone the repo and do "docker-compose up --build"

## Related screenshots

![Screenshot from 2019-12-26 19-10-53](https://user-images.githubusercontent.com/12293878/71478048-91925f00-2813-11ea-9b39-0b2796dea7bb.png)

## System information

Distribution : Ubuntu 18.04
docker-compose : version 1.25.0, build 0a186604
docker : version 19.03.5, build 633a0ea838

**Comment by nikochiko** [comment]
Confirming the issue.
Occurs on Ubuntu 16.04 as well.

**Comment by jayaike** [comment]
@vkartik97 @Ram81 @nikochiko @pushkalkatara @RishabhJain2018 Please what does the LIMIT_CONCURRENT_SUBMISSION_PROCESSING variable return. That seems to be one of the issues.

**Comment by jayaike** [comment]
It should be a string, however, it is not coming that way. I can see that it is an environment variable so perhaps you know the variable's value. 

Pointer: https://github.com/Cloud-CV/EvalAI/blob/master/scripts/workers/submission_worker.py#L41

**Comment by Suryansh5545** [comment]
@vkartik97 told me a alternative **temporary solution** which will make it run . first run the docker container and let the evalai-ngx container exit and then use ng serve to start the front end individually . and you can visit the evalai-ngx front-end at localhost:4200 instead of localhost:8888.
